// 隐私政策与用户协议模板。上线前需由运营者核对并通过环境变量填写主体信息：
// VITE_OPERATOR_NAME（运营者名称）、VITE_CONTACT_EMAIL（联系邮箱）。
// 文本描述的是当前代码实际收集与处理的数据，修改功能时需同步更新。

export interface LegalDoc {
  title: string;
  updated: string;
  sections: { heading: string; paragraphs: string[] }[];
}

type Vars = { operator: string; email: string };

export function privacy(locale: "zh" | "en", v: Vars): LegalDoc {
  if (locale === "en") {
    return {
      title: "Privacy Policy",
      updated: "Last updated: 2026-09-30",
      sections: [
        { heading: "Who we are", paragraphs: [`This site is operated by ${v.operator}. Contact: ${v.email}.`] },
        {
          heading: "What we collect",
          paragraphs: [
            "Account: your email address, a salted hash of your password (never the password itself), an optional display name, and your language preference.",
            "Learning records: works you save, essay drafts, practice you choose to submit to the author and the author's replies, and questions you ask the café historian with the answers.",
            "Workshop applications: the details you enter in the form (name, email, and optional WeChat ID, school, year, exam board, exam session, needs and preferred format).",
            "Technical data: your IP address and browser user agent, used for security, rate limiting and abuse prevention. We use one essential cookie to keep you logged in; we do not use advertising or tracking cookies."
          ]
        },
        {
          heading: "How we use it",
          paragraphs: [
            "To provide the service: keep you logged in, sync your learning records across devices, deliver the author's replies, and send verification codes and service notifications by email.",
            "Questions asked in the café are sent, together with relevant collection notes, to a third-party AI model provider in mainland China to generate an answer. Do not include personal or sensitive information in your questions.",
            "Workshop applications are read by the author only to contact you about the workshop. Registering does not subscribe you to marketing messages."
          ]
        },
        {
          heading: "Storage and retention",
          paragraphs: [
            "Data is stored on servers located in mainland China. We keep account data while your account exists, and delete it within a reasonable time after you ask us to close your account, unless the law requires otherwise."
          ]
        },
        {
          heading: "Your rights",
          paragraphs: [
            `You can view and change your learning records in My Study, and clear your café history at any time. To correct, export or delete your data, or to close your account, email ${v.email}.`
          ]
        },
        { heading: "Minors", paragraphs: ["If you are under 14, please use the site with the consent and guidance of a parent or guardian."] }
      ]
    };
  }
  return {
    title: "隐私政策",
    updated: "更新日期：2026-09-30",
    sections: [
      { heading: "我们是谁", paragraphs: [`本网站由${v.operator}运营。联系邮箱：${v.email}。`] },
      {
        heading: "我们收集哪些信息",
        paragraphs: [
          "账号信息：邮箱、经加盐哈希处理的密码（我们不保存密码原文）、可选的称呼以及语言偏好。",
          "学习记录：你保存的作品、写作草稿、你主动提交给作者的练习及作者回复、你在咖啡馆向艺术史学者提出的问题及回答。",
          "工作坊申请：你在申请表中填写的信息（姓名、邮箱，以及可选的微信号、学校、年级、考试局、考试时间、需求与期望形式）。",
          "技术信息：IP 地址与浏览器标识，用于安全防护、频率限制与防止滥用。我们仅使用一个维持登录状态的必要 Cookie，不使用广告或追踪类 Cookie。"
        ]
      },
      {
        heading: "我们如何使用这些信息",
        paragraphs: [
          "提供服务：保持登录、在不同设备间同步学习记录、向你展示作者回复，并通过邮件发送验证码与服务通知。",
          "你在咖啡馆提出的问题，会连同相关的馆藏笔记发送给中国境内的第三方 AI 模型服务商以生成回答。请不要在提问中填写个人或敏感信息。",
          "工作坊申请仅供作者就工作坊事宜与你联系。注册账号不会让你自动订阅任何营销信息。"
        ]
      },
      {
        heading: "存储与保存期限",
        paragraphs: ["数据存储在中国境内的服务器上。账号存续期间我们保存相关数据；你申请注销后，我们会在合理期限内删除，法律法规另有规定的除外。"]
      },
      {
        heading: "你的权利",
        paragraphs: [
          `你可以在「我的书房」查看和修改学习记录，并随时清空问答记录。如需更正、导出或删除个人信息，或注销账号，请发送邮件至 ${v.email}。`
        ]
      },
      { heading: "未成年人", paragraphs: ["如果你未满 14 周岁，请在父母或其他监护人的同意和指导下使用本网站。"] }
    ]
  };
}

export function terms(locale: "zh" | "en", v: Vars): LegalDoc {
  if (locale === "en") {
    return {
      title: "Terms of Use",
      updated: "Last updated: 2026-09-30",
      sections: [
        { heading: "The service", paragraphs: [`The Art Historian's Common Room is an art-history learning site operated by ${v.operator}. Browsing is free and does not require an account.`] },
        {
          heading: "Learning content and feedback",
          paragraphs: [
            "Collection notes are written for learning and may contain errors; please check important facts against the listed sources.",
            "Essay-room feedback is generated by simple local rules (length, vocabulary and structure cues). It is practice guidance, not AI marking and not an exam grade.",
            "Café answers may come from an AI model or from the collection notes; each answer is labelled. AI answers can be wrong.",
            "The author replies to submitted practice when able. Reply times are not guaranteed, and the service does not include full essay editing or formal exam marking."
          ]
        },
        {
          heading: "Your account and content",
          paragraphs: [
            "Keep your password safe; you are responsible for activity on your account. You keep the rights to what you write. By submitting practice to the author you allow the author to read it and reply.",
            "Do not use the site to post unlawful content, to abuse the AI service or other users, or to interfere with the site's operation. We may suspend accounts that do so."
          ]
        },
        { heading: "Workshop", paragraphs: ["The workshop form registers interest only. Submitting it creates no payment obligation or enrolment; any arrangement is agreed with the author separately."] },
        { heading: "Images", paragraphs: ["Artwork images come from Wikimedia Commons and other open sources under their respective licences; credits are shown on each work page."] },
        { heading: "Contact", paragraphs: [`Questions about these terms: ${v.email}.`] }
      ]
    };
  }
  return {
    title: "用户协议",
    updated: "更新日期：2026-09-30",
    sections: [
      { heading: "关于本服务", paragraphs: [`艺术史公共书房是由${v.operator}运营的艺术史学习网站。浏览内容免费，无需注册。`] },
      {
        heading: "学习内容与反馈",
        paragraphs: [
          "馆藏笔记用于学习参考，可能存在疏漏，重要信息请以所列来源为准。",
          "写作室的反馈由本地规则（字数、词汇与结构提示）生成，是练习参考，不是 AI 批改，也不代表考试分数。",
          "咖啡馆的回答可能来自 AI 模型或馆藏笔记，每条回答都会标明来源。AI 回答可能出错。",
          "作者会在能力范围内回应你提交的练习，不承诺回复时限，也不提供整篇论文修改或正式考试评分。"
        ]
      },
      {
        heading: "账号与内容",
        paragraphs: [
          "请妥善保管密码，账号下的行为由账号持有人负责。你写下的内容归你所有；提交给作者即表示你同意作者阅读并回复。",
          "请勿利用本网站发布违法内容、滥用 AI 服务、骚扰他人或干扰网站运行。对违反者，我们可以暂停其账号。"
        ]
      },
      { heading: "工作坊", paragraphs: ["工作坊申请仅为意向登记，提交后不产生任何付费义务或报名关系，具体安排由作者另行沟通确认。"] },
      { heading: "图片", paragraphs: ["作品图片来自 Wikimedia Commons 等公开来源，按各自许可使用，版权信息见各作品页。"] },
      { heading: "联系我们", paragraphs: [`对本协议有疑问，请联系 ${v.email}。`] }
    ]
  };
}
